version: "3"
services:
  redis:
    image: "redis:4.0"
    ports:
      - "63790:6379"
    volumes:
      - redis_data:/data
  postgres:
    image: "postgres:12"
    container_name: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
      - shared_data:/var/shared
  app:
    build:
      args:
        RUBY_VERSION: '3.0.1'
        NODE_MAJOR: '14'
        BUNDLE_VERSION: '2.2.15'
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3001:3000"
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - postgres
      - redis
  workers:
    build:
      args:
        RUBY_VERSION: '3.0.1'
        NODE_MAJOR: '14'
        BUNDLE_VERSION: '2.2.15'
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
    command: bundle exec sidekiq -q default
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    depends_on:
      - app
      - redis

volumes:
  rails_cache:
  bundle:
  node_modules:
  gem_cache:
  db_data:
  shared_data:
  redis_data:
